FROM python:3.10-alpine

RUN apk add libc-dev
RUN apk add mariadb-dev
RUN apk add gcc
RUN apk add --no-cache mariadb-connector-c-dev

WORKDIR /app

COPY ./app /app

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "15400"]
