spring.datasource.url=jdbc:mariadb://174.138.14.230:3306/desurep?useSSL=false
spring.datasource.username=desuuser
spring.datasource.password=S0siteXui!1User
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
